### ISSUE TITLE
The show goes on

### ISSUE THREAD

**Issue by cinnamoner** [cinnamoner/Just-some-chat-with-the-developer-of-Feren-OS-and-possibly-others-#3]
Common sense appreciated!

**Comment by cinnamoner** [comment]
Feel at home, guys.

**Comment by feren** [comment]
I guess the next one will be 'The show goes on (AGAIN)' then...


Just Kidding. ;D

**Comment by cinnamoner** [comment]
@Elbullazul Welcome!

**Comment by cinnamoner** [comment]
This is a backup thread.
